FROM node:20-alpine AS builder

WORKDIR /app
COPY package.json turbo.json tsconfig.json ./
COPY packages/ ./packages/
COPY apps/ ./apps/

ARG NEXT_PUBLIC_SITE_URL=https://safeschool.org

ENV NEXT_PUBLIC_SITE_URL=$NEXT_PUBLIC_SITE_URL

RUN DATABASE_URL="postgresql://dummy:dummy@localhost:5432/dummy" npm install --legacy-peer-deps
RUN cd apps/web && npm run build

FROM node:20-alpine AS runner

WORKDIR /app
ENV NODE_ENV=production
ENV DATABASE_URL="postgresql://unused:unused@localhost:5432/unused"

COPY --from=builder /app/apps/web/.next/standalone ./
COPY --from=builder /app/apps/web/.next/static ./apps/web/.next/static

ENV HOSTNAME=0.0.0.0
ENV PORT=3000

EXPOSE 3000

CMD ["node", "apps/web/server.js"]
