-- AlterEnum
ALTER TYPE "TimelineActionType" ADD VALUE 'STATUS_CHANGE';
ALTER TYPE "TimelineActionType" ADD VALUE 'MANUAL_ENTRY';
ALTER TYPE "IncidentStatus" ADD VALUE 'ON_SCENE_INCIDENT';
ALTER TYPE "GatewayFailoverReason" ADD VALUE 'PLANNED_MAINTENANCE';
